version: '3.5'
services:
  authority:
    image: 5minds/authority:3.0.0-feature-e441bc-libiob31
    environment:
      CONFIG_PATH: /etc/authority/config/config.json
    volumes:
      - ./.processcube/authority/config.json:/etc/authority/config/config.json
      - ./.processcube/authority/users.json:/etc/authority/config/users.json
    ports:
      - '11560:11560'

  portal:
    image: 5minds/portal:4.0.0-alpha.4
    environment:
      CONFIG_PATH: /etc/portal/config/config.json
    volumes:
      - ./.processcube/portal/config.json:/etc/portal/config/config.json
    ports:
      - '8082:8082'

  engine:
    image: 5minds/engine:14.2.4
    environment:
      CONFIG_PATH: /etc/engine/config/config.json
    volumes:
      - ./.processcube/engine/config.json:/etc/engine/config/config.json:ro
    ports:
      - '8000:8000'
