version: "3.5"
services:
  authority:
    image: 5minds/processcube_authority:2023-2
    environment:
      CONFIG_PATH: /etc/authority/config/config.json
      UPE_SEED_PATH: /etc/authority/config/upeSeedingData.json
    volumes:
      - ./.processcube/authority/config.json:/etc/authority/config/config.json
      - ./.processcube/authority/upeSeedingData.json:/etc/authority/config/upeSeedingData.json
    ports:
      - 11560:11560

  engine:
    image: 5minds/processcube_engine:2023-2
    environment:
      CONFIG_PATH: /etc/engine/config/config.json
    volumes:
      - ./.processcube/engine/config.json:/etc/engine/config/config.json:ro
    ports:
      - 8000:8000
